config {
  type: "incremental"
}


-- ブラウザ単位で1つ前のアクセス時刻を取得／不要データの除外
WITH sub_t AS (

SELECT 
  member_id,
  timestamp_trunc(access_timestamp,DAY) AS access_day,--訪問日の取得
  access_timestamp,
  LAG ( access_timestamp, 1) OVER (PARTITION BY  member_id ORDER BY access_timestamp) AS lag_1_access_timestamp --1つ前のアクセス時刻（会員単位）
FROM `test-nikkei.test_nikkei.access_logs_sample`
WHERE internal_access = False --社内アクセスの除外
      AND member_id IS NOT NULL --ユニークブラウザ数を取得するため、member_id＝Nullは不要。かつ、Nullのレコード数が全体の3割超を占めるため、処理軽量化のため除外
      
      -- 更新を前の日のデータのみとする
      AND DATE(access_timestamp, "Asia/Tokyo")  = DATE_SUB('2023-04-02', INTERVAL 1 DAY)
      -- AND DATE(access_timestamp, "Asia/Tokyo")  = DATE_SUB(CURRENT_DATE("Asia/Tokyo"), INTERVAL 1 DAY)
      
)

-- アクセス日時の抽出／各ブラウザIDの一つ前のアクセスからの経過時間を取得／
,sub_t_2 AS(
SELECT 
  member_id,
  access_day,--アクセス日時
  timestamp_trunc(lag_1_access_timestamp,DAY) AS lag_1_access_day,--ひとつ前のアクセスの日時
  
  access_timestamp,
  lag_1_access_timestamp,
  TIMESTAMP_DIFF(access_timestamp, lag_1_access_timestamp, MINUTE) AS diff_access--ひとつ前のアクセスとの差分（分数）。訪問を区切る際に使用
FROM sub_t
)

--「訪問」ログにデータを絞り込む
,sub_t_3 AS (
SELECT
  member_id,
  access_day,
  lag_1_access_day,
  access_timestamp,
  lag_1_access_timestamp,
  diff_access
FROM sub_t_2
WHERE
-- 以下ケースが「訪問」に該当
  lag_1_access_timestamp IS NULL  --ケース1＿各ブラウザの最初のアクセスの場合
  OR diff_access>=30              --ケース2＿各ブラウザ単位で一つ前のアクセスからの経過時間が30以上たった場合
  OR access_day!=lag_1_access_day --ケース3＿各ブラウザ単位で一つ前のアクセスが日を跨ぐ場合

)

-- ブラウザごと、かつ、訪問日ごとにアクセス回数を算出
,sub_t_4 AS (
SELECT
  member_id,
  access_day,
  COUNT(*) AS access_times
FROM sub_t_3
GROUP BY 1,2
)

-- 「（訪問）日ごとに」「何回訪問した人が」「何ユーザー(ブラウザ)」いたか算出
SELECT 
  access_day,
  access_times,
  COUNT(DISTINCT member_id) AS member_id_count --ユニークブラウザ数
FROM sub_t_4
GROUP BY 1,2
ORDER BY 1,2 --視認性向上のため、日付・訪問回数で昇順並び替え